# -*- coding: utf-8 -*-
"""Spacy demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tvE9fnbPAJ2tVhVZvfmkcNxgDMPnMQ53
"""

!pip install -U spacy

!python -m spacy download en

import spacy

nlp = spacy.load('en')

print(nlp)

!wget "https://gist.githubusercontent.com/github-gist-bot/93e5d7fc085a0c2fdc819eed1a0962f5/raw/8d576e3eebd8edc50a3f9849d2b4e5a48b4d3c71/github_gist_bot.txt" -O newfile.txt

lineList = [line.rstrip('\n') for line in open('newfile.txt')]

def extract_relations(doc):
    # merge entities and noun chunks into one token
    spans = list(doc.ents) + list(doc.noun_chunks)
    for span in spans:
        span.merge()

    relations = []
    for money in filter(lambda w: w.ent_type_ == 'MONEY', doc):
        if money.dep_ in ('attr', 'dobj'):
            subject = [w for w in money.head.lefts if w.dep_ == 'nsubj']
            if subject:
                subject = subject[0]
                relations.append((subject, money))
        elif money.dep_ == 'pobj' and money.head.dep_ == 'prep':
            relations.append((money.head.head, money))
    return relations

for text in lineList:
        doc = nlp(text)
        relations = extract_relations(doc)
        for r1, r2 in relations:
            print('{:<10}\t{}\t{}'.format(r1.text, r2.ent_type_, r2.text))

import spacy
from spacy import displacy
nlp = spacy.load("en")
import warnings
warnings.filterwarnings('ignore',category=UserWarning)
'''
d = open("report4.txt","r",encoding = "utf8")
x = d.read()
'''
for text in lineList:
  
  
  wt = nlp(text)
  for w in wt.ents:
    
    print(w,text,w.label_)  
  
  
  displacy.render(wt,style="ent",jupyter=True)

!pip install news-please

from newsplease import NewsPlease
article = NewsPlease.from_html('https://www.customs.gov.hk/en/publication_press/press/index_current.html')
print(article.title)

